package controllers

import (
	"fmt"

	"encoding/json"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type UserAddController struct {
	beego.Controller
}

type SQLuserinfo struct {
	Uid      int    `orm:"pk;auto"`
	Username string `orm:"unique;column(username)"`
	Password string `orm:"column(password)"`
	Nickname string `orm:"column(nickname)"`
	Coins    int    `orm:"column(coins)"`
}

/*
	This function add a user to mysql and
	return the ID generated by mysql.
*/
func init() {
	orm.RegisterDriver("mysql", orm.DRMySQL)
	orm.RegisterDataBase("default", "mysql", "aixinwu:aixinwu@tcp(localhost:3306)/appdev?charset=utf8")
	orm.RegisterModel(new(SQLuserinfo))
}

func createTable() {
	name := "default"
	force := false
	verbose := true
	err := orm.RunSyncdb(name, force, verbose)
	if err != nil {
		beego.Error(err)
	}
}

func checkUserExist(name string) (bool, error) {
	return true,nil
}

func addUser(usrinfo TypeUserInfo) (string, error) {
	o := orm.NewOrm()
	o.Using("default")
	createTable()
	fmt.Println(o)
	s := SQLuserinfo{
		Username: usrinfo.Username,
		Password: usrinfo.Password,
		Nickname: usrinfo.NickName,
		Coins:    0,
	}
	retval, err := o.Insert(&s)
	if err != nil {
		return "", err
	}
	return fmt.Sprint(retval), nil
}

func (c *UserAddController) Post() {
	beego.Debug("add user")
	info := TypeUserInfo{}
	beego.Info("Post Body is:", string(c.Ctx.Input.RequestBody))
	err := json.Unmarshal(c.Ctx.Input.RequestBody, &info)
	ErrReport(err)
	if err != nil {
		c.Abort("500")
		return
	}
	retval := TypeRegularResp{
		MataData: GenMataData(),
	}
	// check username and psw
	_, err = addUser(info)
	retval.Status = GenStatus(StatusCodeOK)
	c.Data["json"] = retval
	c.ServeJSON()

}
