package controllers

import (
	"encoding/json"
	"github.com/astaxie/beego"
	_ "github.com/go-sql-driver/mysql"
)

type UserAddController struct {
	beego.Controller
}

/*
	This function add a user to mysql and
	return the ID generated by mysql.
*/

func (c *UserAddController) Post() {
	beego.Debug("add user")
	info := TypeUserInfo{}
	body := c.Ctx.Input.CopyBody(beego.AppConfig.DefaultInt64("bodybuffer", 1024*1024))
	beego.Info("Post Body is:", string(body))
	err := json.Unmarshal(body, &info)
	ErrReport(err)
	if err != nil {
		c.Abort("500")
		return
	}
	retVal := TypeRegularResp{
		MataData: GenMataData(),
	}
	// check username and psw
	_, err = AddUser(info)
	retVal.Status = GenStatus(StatusCodeOK)
	c.Data["json"] = retVal
	c.ServeJSON()

}
